---

- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: 
        name: nginx
        state: latest
      become: yes
    
    - name: start nginx 
      service:
        name: nginx
        state: started
      become: yes
    
    - name: copy the content of the website
      copy:
        src: /home/pawel/www/src/
        dest: /home/pawel/www/site

    - name: copy the nginx config file
      copy:
        src: /home/pawel/www/site/static_site.cfg
        dest: /etc/nginx/sites-available/static_site.cfg

    - name: create symlink
      file:
         src: /etc/nginx/sites-available/static_site.cfg
         dest: /etc/nginx/sites-enabled/default
         state: link

    - name: restart nginx service
      service:
        name: nginx
        state: restarted      