---
# tasks file for check_uptime
- name: Capture timestamp
  shell: date +"%Y-%m-%d-%H:%M:%S"
  register: current_date_time

- name: Check Uptime
  shell: "uptime"
  register: uptime

- name: Output Uptime
  debug: msg={{ uptime.stdout_lines }}

- name: Output CurrentDateTime
  debug: msg={{ current_date_time.stdout_lines }}